---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    # yum install -y haproxy
    - yum:
        name: haproxy
        state: installed

    # systemctl start haproxy
    - systemd:
        name: haproxy
        enabled: yes
        state: started
